-- Recipient Claim / Add to Collection Flow — one new atomic SECURITY
-- DEFINER RPC letting the current owner of an unlinked registered card
-- (most commonly a transfer recipient post-accept) create a brand-new
-- collection_items row for themselves and link it back to the existing
-- Cache ID in one transaction. Mirrors link_registered_card_collection_item's
-- own authorization shape (auth required, row-locked, current_owner_id
-- check, item_linked registry event) but never accepts an externally
-- supplied collection_item_id — the item is always created inside this
-- same function, for auth.uid(), so it is impossible to link to another
-- user's existing item through this path.
--
-- image_url is always set NULL at creation time — the durable registry
-- snapshot image (when snapshot_image_status = 'ready') is copied in by
-- the client only AFTER this RPC has already committed successfully, via
-- a plain follow-up Storage upload + collection_items UPDATE (both already
-- permitted by existing RLS: item_images_insert_own, items_update_own).
-- This keeps the atomic claim itself independent of Storage/network
-- calls entirely, and means a later image-copy failure can never affect
-- (or need to roll back) the already-completed claim. See
-- lib/registry-claim.ts and app/claim-card/[id].tsx for the client side.
--
-- Only reads registered_cards (by id, already the caller's own per the
-- ownership check) and folders (by id, already the caller's own per the
-- ownership check) — never collection_items except to INSERT the new row,
-- so the former owner's original collection item is never read.
--
-- p_year is smallint, matching collection_items.year's live column type
-- exactly (confirmed via information_schema — not integer).

CREATE OR REPLACE FUNCTION public.claim_registered_card(
  p_registered_card_id uuid,
  p_folder_id uuid,
  p_title text DEFAULT NULL::text,
  p_player text DEFAULT NULL::text,
  p_year smallint DEFAULT NULL::smallint,
  p_brand text DEFAULT NULL::text,
  p_team text DEFAULT NULL::text,
  p_grade text DEFAULT NULL::text,
  p_grading_company text DEFAULT NULL::text,
  p_serial_number text DEFAULT NULL::text
)
 RETURNS collection_items
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_caller_id uuid := auth.uid();
  v_card      public.registered_cards;
  v_item      public.collection_items;
BEGIN
  IF v_caller_id IS NULL THEN
    RAISE EXCEPTION 'Authentication required';
  END IF;

  SELECT * INTO v_card FROM public.registered_cards WHERE id = p_registered_card_id FOR UPDATE;
  IF v_card.id IS NULL THEN
    RAISE EXCEPTION 'Registered card not found';
  END IF;
  IF v_card.current_owner_id IS DISTINCT FROM v_caller_id THEN
    RAISE EXCEPTION 'Only the current owner may claim this card';
  END IF;
  IF v_card.collection_item_id IS NOT NULL THEN
    RAISE EXCEPTION 'This card is already linked to a collection item';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM public.folders f WHERE f.id = p_folder_id AND f.user_id = v_caller_id
  ) THEN
    RAISE EXCEPTION 'Folder not found or not owned by caller';
  END IF;

  -- image_url is always NULL here by design — see the migration header
  -- comment above. user_id is always v_caller_id, never client-supplied,
  -- so this can never create an item "for" another user.
  INSERT INTO public.collection_items (
    folder_id, user_id, title, player, year, brand, team,
    grade, grading_company, serial_number, image_url
  ) VALUES (
    p_folder_id, v_caller_id, p_title, p_player, p_year, p_brand, p_team,
    p_grade, p_grading_company, p_serial_number, NULL
  )
  RETURNING * INTO v_item;

  -- No unique-violation handling needed here (unlike
  -- link_registered_card_collection_item, which can target an existing,
  -- possibly-already-linked item): v_item.id is freshly generated by the
  -- INSERT above and cannot already be referenced by any other
  -- registered_cards row.
  UPDATE public.registered_cards
  SET collection_item_id = v_item.id, updated_at = now()
  WHERE id = p_registered_card_id;

  INSERT INTO public.registry_events (registered_card_id, event_type, actor_id, metadata)
  VALUES (p_registered_card_id, 'item_linked', v_caller_id, jsonb_build_object('collection_item_id', v_item.id));

  RETURN v_item;
END;
$function$;

REVOKE EXECUTE ON FUNCTION public.claim_registered_card(uuid, uuid, text, text, smallint, text, text, text, text, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.claim_registered_card(uuid, uuid, text, text, smallint, text, text, text, text, text) FROM anon;
GRANT EXECUTE ON FUNCTION public.claim_registered_card(uuid, uuid, text, text, smallint, text, text, text, text, text)
  TO authenticated;

NOTIFY pgrst, 'reload schema';
